// Auto-generated from TestClass.cs

import TestClass2 from './TestClass2';
import TestClassInFolder from './SubFolder1/SubFolder2/TestClassInFolder';
import GenericClass1 from './GenericClass1';
import TestEnum from './TestEnum';
import GenericClass2 from './GenericClass2';
import TestEnumInFolder from './Enums/TestEnumInFolder';

interface TestClass {
  intProperty: number;
  nullableIntProperty: number | null;
  longProperty: number;
  nullableLongProperty: number | null;
  floatProperty: number;
  nullableFloatProperty: number | null;
  doubleProperty: number;
  nullableDoubleProperty: number | null;
  decimalProperty: number;
  nullableDecimalProperty: number | null;
  boolProperty: boolean;
  nullableBoolProperty: boolean | null;
  charProperty: string;
  nullableCharProperty: string | null;
  byteProperty: number;
  nullableByteProperty: number | null;
  sByteProperty: number;
  nullableSByteProperty: number | null;
  shortProperty: number;
  nullableShortProperty: number | null;
  uShortProperty: number;
  nullableUShortProperty: number | null;
  uIntProperty: number;
  nullableUIntProperty: number | null;
  uLongProperty: number;
  nullableULongProperty: number | null;
  stringProperty: string;
  nullableStringProperty: string;
  guidProperty: string;
  nullableGuidProperty: string | null;
  dateTimeProperty: Date;
  nullableDateTimeProperty: Date | null;
  dateTimeOffsetProperty: Date;
  nullableDateTimeOffsetProperty: Date | null;
  thisClass: TestClass;
  class2: TestClass2;
  classInFolder: TestClassInFolder;
  genericClass1: GenericClass1<TestClass>;
  genericClass2: GenericClass2<TestClass, TestEnum>;
  enum: TestEnum;
  nullableEnum: TestEnum | null;
  enumInFolder: TestEnumInFolder;
  formFile: File;
  iFormFile: File;
  intEnumerable: number[];
  intCollection: number[];
  intIList: number[];
  intList: number[];
  intArray: number[];
  intDictionary: { [key: string]: number };
  intIDictionary: { [key: string]: number };
  intHashSet: number[];
  intISet: number[];
  intQueue: number[];
  intStack: number[];
  intLinkedList: number[];
  intSortedSet: number[];
  intSortedList: { [key: string]: number };
  intSortedDictionary: { [key: string]: number };
  intReadOnlyCollection: number[];
  intReadOnlyList: number[];
  intReadOnlyDictionary: number[];
  intCollection2: number[];
  intConcurrentBag: number[];
  formFileCollection: File[];
  iFormFileCollection: File[];
  nullableIntEnumerable: (number | null)[];
  nullableIntCollection: (number | null)[];
  nullableIntIList: (number | null)[];
  nullableIntList: (number | null)[];
  nullableIntArray: (number | null)[];
  nullableIntDictionary: { [key: string]: (number | null) };
  nullableIntIDictionary: { [key: string]: (number | null) };
  nullableIntHashSet: (number | null)[];
  nullableIntISet: (number | null)[];
  nullableIntQueue: (number | null)[];
  nullableIntStack: (number | null)[];
  nullableIntLinkedList: (number | null)[];
  nullableIntSortedSet: (number | null)[];
  nullableIntSortedList: { [key: string]: (number | null) };
  nullableIntSortedDictionary: { [key: string]: (number | null) };
  nullableIntReadOnlyCollection: (number | null)[];
  nullableIntReadOnlyList: (number | null)[];
  nullableIntReadOnlyDictionary: (number | null)[];
  nullableIntCollection2: (number | null)[];
  nullableIntConcurrentBag: (number | null)[];
}

export default TestClass;
